info:
  title: Project YaCut
  version: 0.1.0
tags: []
paths:
  /api/id/:
    post:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_id_rec'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create_id'
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Empty request:
                  value:
                    message: Missing request body
                Invalid short identifier:
                  value:
                    message: "Invalid name specified for short link"
                Missing a required field:
                  value:
                    message: '"url" is a required field!'
          description: Not found
      summary: Create Id
  /api/id/{short_id}/:
    get:
      parameters:
        - in: path
          name: short_id
          schema:
            type: string
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_url'
          description: Successful response
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Non-existent id:
                  value:
                    message: The specified id was not found.
          description: Not found
      summary: Get Url
openapi: 3.0.3
components:
  schemas:
    Error:
      properties:
        message:
          type: string
      type: object
    get_url:
      properties:
        url:
          type: string
      type: object
      description: Getting a link by ID
    create_id:
      properties:
        url:
          type: string
        short_link:
          type: string
      type: object
      description: Generation of a new link
    create_id_rec:
      properties:
        url:
          type: string
        custom_id:
          type: string
      type: object
      required:
          - url
      description: Generation of a new link
